[workspace]
members = [
  "openapi",
  "bench/binary_size",
  "crates/async_stripe",
  "crates/async_stripe_client",
  "crates/generated/*",
]

# [dev-dependencies]
# actix-web = "4.0.1"
# anyhow = "1.0.38"
# async-std = {version = "1.10.0", features = ["attributes"]}
# axum = "0.4.8"
# httpmock = "0.6.6"
# lazy_static = "1.4"
# tokio = {version = "1.2", features = ["rt", "macros"]}

# [[example]]
# name = "checkout"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "connect"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "customer"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "payment-intent"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "payment-link"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "subscriptions"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "webhook-axum"
# required-features = ["runtime-tokio-hyper"]

# [[example]]
# name = "webhook-actix"
# required-features = ["runtime-tokio-hyper"]
